version: '3.9'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    container_name: mysql-db-test
    volumes:
      - mysql_data:/var/lib/mysql
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_SYNC=true
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_PORT=${DATABASE_PORT}
    ports:
      - "3000:3000"
    container_name: nest-postgres
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  mysql_data: